### PR TITLE
Bugfix logo

### PR DESCRIPTION
**Pull request by AdrianSosic**
Add the logo to the package content so that it can be displayed in the demo

### CODE REVIEW

**Comment by AdrianSosic** [comment]
@dasmy: issue with importlib.resources and python < 3.8 still exists but is not covered by our tests (only occurs in the demo currently). Please don't merge before we haven't fixed it =)

**Comment by AdrianSosic** [comment]
@dasmy btw: just noticed that our readme says python > 3.6 but setup.cfg says python > 3.7. Probably we should fix both problems simultaneously

**Comment by dasmy** [comment]
Hi @AdrianSosic ,
According to https://docs.python.org/3.7/library/importlib.html?highlight=importlib#module-importlib.resources and https://stackoverflow.com/a/20885799 , importlib.resources is available from 3.7 on.

This, I guess it will be easiest if we require python 3.7 or higher (as we already do in setup.cfg and in pytest.yml)

**Comment by AdrianSosic** [comment]
Hi @dasmy 
Perfect. I suggest we implement simple test to verify if the demo and the examples run without any errors (to ensure that all import run smoothly in all python versions) and if all tests pass, we merge the branch and create a bugfix release 0.1.1

**Comment by AdrianSosic** [comment]
will resolve #29

**Comment by AdrianSosic** [comment]
@dasmy: I've added the missing platform/license identifiers and created the corresponding changelog entry for 0.1.1. Please have a quick look if everything is fine before I release it

**Comment by dasmy** [comment]
@AdrianSosic ,
looks good to me. - Go for it :-)

**Pull request merged**
